apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  labels:
    eventstreams.ibm.com/cluster: myes
  name: my-topic-internet
  namespace: cp4i
spec:
  config: {}
  partitions: 1
  replicas: 3
  topicName: my-topic-internet