apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-kafka
  name: my-topic-internet
  namespace: strimzi
spec:
  config: {}
  partitions: 1
  replicas: 3
  topicName: my-topic-internet
